version: 2
jobs:
  build:
    working_directory: ~/build
    docker:
      - image: circleci/node:6.10.3
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install packages
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: run eclint
          command: yarn eclint
      - run:
          name: run tslint
          command: yarn tslint
      - run:
          name: compile project
          command: yarn compile
      - run:
          name: build project
          command: yarn build:prod
      